USE [master]
GO

DECLARE @dbname nvarchar(128)
SET @dbname = N'EA2'

IF (EXISTS (SELECT name 
FROM master.dbo.sysdatabases 
WHERE ('[' + name + ']' = @dbname 
OR name = @dbname)))
DROP database [EA2]
GO

CREATE DATABASE [EA2]
GO
ALTER DATABASE [EA2] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EA2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EA2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EA2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EA2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EA2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EA2] SET ARITHABORT OFF 
GO
ALTER DATABASE [EA2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EA2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EA2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EA2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EA2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EA2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EA2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EA2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EA2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EA2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EA2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EA2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EA2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EA2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EA2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EA2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EA2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EA2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EA2] SET  MULTI_USER 
GO
ALTER DATABASE [EA2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EA2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EA2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EA2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [EA2] SET DELAYED_DURABILITY = DISABLED 
GO
USE [EA2]
GO
/****** Object:  Table [dbo].[Competidores]******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Competidores](
	[IdCompetidor] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Competidores] PRIMARY KEY CLUSTERED 
(
	[IdCompetidor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[Premios]******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Premios](
	[IdPremio] [int] IDENTITY(1,1) NOT NULL,
	[IdCompetidor] [int] NOT NULL,
	[CantidadPremios] [int] NOT NULL,
	[Anio] [int] NOT NULL,
 CONSTRAINT [PK_Premios] PRIMARY KEY CLUSTERED 
(
	[IdPremio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [dbo].[Premios]  WITH CHECK ADD  CONSTRAINT [FK_Competidores_Premios] FOREIGN KEY([IdCompetidor])
REFERENCES [dbo].[Competidores] ([IdCompetidor])
GO

USE [master]
GO
ALTER DATABASE [EA2] SET  READ_WRITE 
GO

USE [EA2]
GO