//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premios
    {
        public int IdPremio { get; set; }
        public int IdCompetidor { get; set; }
        public int CantidadPremios { get; set; }
        public int Anio { get; set; }
    
        public virtual Competidores Competidores { get; set; }
    }
}
